name: 重複しているタグがないかをvalidate

on:
  workflow_dispatch:
  schedule:
    # UTCの01:00はJSTだと10:00
    - cron: '0 1 * * *'

jobs:
  tags_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: '24'
    - run: npm install
    - name: 重複しているタグがないかvalidation
      env:
        ESA_TEAM_NAME: ${{ secrets.ESA_TEAM_NAME }}
        ESA_ACCESS_TOKEN: ${{ secrets.ESA_ACCESS_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: npx ts-node src/tags_validator.ts
