name: 重複しているタグがないかをvalidate

on:
  workflow_dispatch:
  schedule:
    # UTCの01:00はJSTだと10:00
    - cron: '0 1 * * *'

jobs:
  tags_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: '24'
    - run: npm install
    - name: 重複しているタグがないかvalidation
      env:
        ESA_TEAM_NAME: ${{ secrets.ESA_TEAM_NAME }}
        ESA_ACCESS_TOKEN: ${{ secrets.ESA_ACCESS_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: npx ts-node src/tags_validator.ts
